# Generated by Django 5.0.6 on 2024-06-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseForm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramtask',
            name='weekday',
            field=models.SmallIntegerField(),
        ),
    ]
