# Generated by Django 5.0.6 on 2024-06-03 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseForm', '0002_alter_telegramtask_weekday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramtask',
            old_name='user_id',
            new_name='user',
        ),
    ]
