# Generated by Django 5.0.6 on 2024-06-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseForm', '0003_rename_user_id_telegramtask_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramtask',
            name='user',
            field=models.PositiveBigIntegerField(),
        ),
    ]
